dist: xenial
language: python
services:
  - memcached
  - redis-server
addons:
  postgresql: "10"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test2;' -U postgres
install:
  - pip install -U pip  # make sure we have the latest version
  - pip install -e .
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls

matrix:
  include:
    - python: 3.5
      env: TOX_ENV="dj220-py35,dj300-py35"
    - python: 3.6
      env: TOX_ENV="dj220-py36"
    - python: 3.7
      env: TOX_ENV="dj220-py37,dj300-py37,dj310-py37,py37-flake8"
    - python: 3.8
      env: TOX_ENV="dj220-py38,dj300-py38,dj310-py38,py38-flake8,docs"

# Adding sudo: False tells Travis to use their container-based infrastructure, which is somewhat faster.
sudo: False
